server:
  port: 8888

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          # uri: file:////home/jongyunha/Documents/code/msa-config
          uri: https://github.com/nothingprogram/spring-cloud-config.git
          # username: [ your username ]
          # password: [ your password ]

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh